# Development docker-compose file with server auto-reload and
# code mounted as a volume.
app:
    image: eeacms/esbootstrap:latest
    ports: # App accessible on http://localhost:3000
        - 3090:3000
    volumes_from: # Mount code as a volume for easy restart
        - esbootstrap-data-config
    environment: # Use current upstream staging instance
        - elastic_host=10.201.1.153
        - APP_CONFIG_DIRNAME=default
        - NODE_ENV=dev # Change to production if you want to test the app in production environment
    entrypoint:
        - /node_modules/.bin/nodemon
        - /code/app.js
        - --watch
        - /code/config/*/settings.json
    command:
        - runserver
    volumes:
        - ./app/public:/code/public:z
        - /var/local/deploy/eea.docker.searchservices/eea.searchserver.js/lib:/node_modules/eea-searchserver/lib:z
        - ./app/config/:/code/config/:z

ide:
    image: eeacms/cloud9
    volumes_from:
        - esbootstrap-data-config
    ports:
        - 8001:8080
    environment:
        - C9_WORKSPACE=/code/config
        
esbootstrap-data-config:
    image: eeacms/esbootstrap-configs
    environment:
        - github_repo=https://github.com/eea/eea.esbootstrap.configs
    volumes:
        - /code/config
