# Development docker-compose file with server auto-reload and
# code mounted as a volume.
app:
    image: esbootstrapmy2
    ports: # App accessible on http://localhost:3000
        - 3000:8080
    volumes: # Mount code as a volume for easy restart
        - ./app/:/code/:z
    environment: # Use current upstream staging instance
        - elastic_host=10.201.1.97
        - APP_CONFIG_DIRNAME=default2
        - NODE_ENV=dev # Change to production if you want to test the app in production environment